### ISSUE TITLE
Some related ideas

### ISSUE THREAD

**Issue by zoechi** [DirectMyFile/dep-spaceship#1]
http://dartbug.com/1492

**Comment by seaneagan** [comment]
Yeah, `a <=> b` is slightly more readable than  `a.compareTo(b)`, but I'm not sure that's worth the cost of having two ways to do the same thing.

I think the bigger problem is the disconnect between `compareTo`/`Comparable` and comparison operators (`< <= == > >=` and potentially `min`, `max`, `clamp`, `isBetween`).  The [contrast package](https://pub.dartlang.org/packages/contrast) has a `Quantity` mixin for this, but it would be nice if that were just in `dart:core`, and if classes there implemented it e.g. `num`, `String`, `Duration`, `Date`.
